-- V1__init_org.sql
-- Rainier organization-dimension schema bootstrap.
-- Engine: InnoDB. Charset: utf8mb4. Collation: utf8mb4_0900_ai_ci (MySQL 8 default).
-- Identifiers: 32-char UUID hex (no dashes), generated by Hibernate UUIDHexGenerator.
-- Audit fields populated by JPA Auditing (BaseEntity); del_flag is part of the global
-- soft-delete pattern (Organization + User opt in; UserOrganization keeps the column at 0).

-- MariaDB 10.6 default collation differs from MySQL 8 (uca1400_ai_ci vs utf8mb4_0900_ai_ci);
-- omit explicit COLLATE per-table so the connection default applies, which keeps the
-- script portable across both engines.
SET NAMES utf8mb4;

-- ---------------------------------------------------------------------------------------------
-- rainier_organization — self-referential tree (COMPANY → DEPARTMENT → DOMAIN → TEAM → SUBGROUP)
-- ---------------------------------------------------------------------------------------------
CREATE TABLE rainier_organization (
  id           VARCHAR(32)  NOT NULL                            COMMENT 'UUID hex (no dashes)',
  parent_id    VARCHAR(32)  NULL                                COMMENT 'NULL for root nodes',
  type         VARCHAR(16)  NOT NULL                            COMMENT 'COMPANY|DEPARTMENT|DOMAIN|TEAM|SUBGROUP',
  code         VARCHAR(64)  NOT NULL                            COMMENT 'Business code; unique within parent',
  name         VARCHAR(100) NOT NULL                            COMMENT 'Display name',
  description  VARCHAR(500) NULL,
  path         VARCHAR(200) NULL                                COMMENT 'Denormalized ancestor chain: /rootId/.../selfId',
  whole_name   VARCHAR(500) NULL                                COMMENT 'Denormalized full path name: A/B/C',
  is_pmo       TINYINT(1)   NOT NULL DEFAULT 0                  COMMENT 'PMO team marker (role card §2.2)',
  enabled      TINYINT(1)   NOT NULL DEFAULT 1                  COMMENT '1=enabled, 0=disabled',
  del_flag     TINYINT(1)   NOT NULL DEFAULT 0                  COMMENT '0=normal, 1=soft-deleted',
  create_by    VARCHAR(32)  NULL                                COMMENT 'Auditor username',
  create_time  DATETIME(6)  NOT NULL,
  update_by    VARCHAR(32)  NULL,
  update_time  DATETIME(6)  NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_rainier_organization_parent_code (parent_id, code),
  KEY idx_rainier_organization_parent (parent_id),
  KEY idx_rainier_organization_type (type),
  KEY idx_rainier_organization_del_flag (del_flag),
  CONSTRAINT fk_rainier_organization_parent
    FOREIGN KEY (parent_id) REFERENCES rainier_organization (id)
    ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
  COMMENT='Organization dimension adjacency-list tree';

-- ---------------------------------------------------------------------------------------------
-- rainier_user — person (minimal: identity + flags + audit)
-- ---------------------------------------------------------------------------------------------
CREATE TABLE rainier_user (
  id             VARCHAR(32)  NOT NULL                          COMMENT 'UUID hex',
  login_name     VARCHAR(30)  NOT NULL                          COMMENT 'Login identifier',
  name           VARCHAR(30)  NOT NULL                          COMMENT 'Real name',
  code           VARCHAR(30)  NULL                              COMMENT 'Employee number',
  email_address  VARCHAR(255) NULL,
  is_internal    TINYINT(1)   NOT NULL DEFAULT 1                COMMENT '1=internal, 0=external',
  enabled        TINYINT(1)   NOT NULL DEFAULT 1,
  del_flag       TINYINT(1)   NOT NULL DEFAULT 0,
  create_by      VARCHAR(32)  NULL,
  create_time    DATETIME(6)  NOT NULL,
  update_by      VARCHAR(32)  NULL,
  update_time    DATETIME(6)  NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_rainier_user_login_name (login_name),
  UNIQUE KEY uk_rainier_user_code (code),
  UNIQUE KEY uk_rainier_user_email (email_address),
  KEY idx_rainier_user_is_internal (is_internal),
  KEY idx_rainier_user_del_flag (del_flag)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
  COMMENT='Person identity';

-- ---------------------------------------------------------------------------------------------
-- rainier_user_organization — M2M assignment of users to organizations
-- (Hard delete; left_at non-null marks the historical record. del_flag column inherited from
-- BaseEntity is unused but kept for schema consistency.)
-- ---------------------------------------------------------------------------------------------
CREATE TABLE rainier_user_organization (
  id              VARCHAR(32)  NOT NULL                         COMMENT 'UUID hex',
  user_id         VARCHAR(32)  NOT NULL,
  organization_id VARCHAR(32)  NOT NULL,
  role            VARCHAR(16)  NOT NULL DEFAULT 'MEMBER'        COMMENT 'MEMBER|HEAD',
  is_primary      TINYINT(1)   NOT NULL DEFAULT 0               COMMENT 'Primary affiliation; service layer ensures ≤ 1 per user',
  joined_at       DATETIME(6)  NOT NULL,
  left_at         DATETIME(6)  NULL                             COMMENT 'NULL=active, non-NULL=historical',
  del_flag        TINYINT(1)   NOT NULL DEFAULT 0               COMMENT 'Inherited from BaseEntity; unused (hard delete)',
  create_by       VARCHAR(32)  NULL,
  create_time     DATETIME(6)  NOT NULL,
  update_by       VARCHAR(32)  NULL,
  update_time     DATETIME(6)  NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_rainier_user_org_pair (user_id, organization_id),
  KEY idx_rainier_user_org_user (user_id),
  KEY idx_rainier_user_org_org (organization_id),
  KEY idx_rainier_user_org_role (role),
  CONSTRAINT fk_rainier_user_org_user
    FOREIGN KEY (user_id) REFERENCES rainier_user (id) ON DELETE RESTRICT,
  CONSTRAINT fk_rainier_user_org_org
    FOREIGN KEY (organization_id) REFERENCES rainier_organization (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
  COMMENT='Person ↔ organization M2M with role + history';
