/* (C) 2026 Rainier — internal use only. */
package com.rainier.weekly.domain;

import com.rainier.common.persistence.BaseEntity;
import java.time.Instant;
import java.time.LocalDate;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Lob;
import javax.persistence.Table;

/**
 * v0.0.71 — a user's weekly report draft, generated by the rule-template "AI" pass and pending a
 * human accept. {@link WeeklyDraftStatus} encodes the 3-state machine (DRAFT → ACCEPTED → SENT);
 * actual SENT transition + push is out of scope for A7.
 *
 * <p>No {@code @SQLDelete} — drafts are kept for audit; only {@code status} mutates on a decision.
 */
@Entity
@Table(name = "rainier_weekly_draft")
public class WeeklyDraft extends BaseEntity {

  /** Author of this weekly. Soft FK → {@code rainier_user.id}. */
  @Column(name = "user_id", nullable = false)
  private Long userId;

  @Column(name = "period_start", nullable = false)
  private LocalDate periodStart;

  @Column(name = "period_end", nullable = false)
  private LocalDate periodEnd;

  /** Markdown body — assembled by template rules in v0.0.71; LLM-replaced in a later iteration. */
  @Lob
  @Column(name = "content_markdown", nullable = false)
  private String contentMarkdown;

  @Column(nullable = false, length = 16)
  private String status = WeeklyDraftStatus.DRAFT;

  @Column(name = "created_at", nullable = false)
  private Instant createdAt;

  @Column(name = "accepted_at")
  private Instant acceptedAt;

  public Long getUserId() {
    return userId;
  }

  public void setUserId(Long userId) {
    this.userId = userId;
  }

  public LocalDate getPeriodStart() {
    return periodStart;
  }

  public void setPeriodStart(LocalDate periodStart) {
    this.periodStart = periodStart;
  }

  public LocalDate getPeriodEnd() {
    return periodEnd;
  }

  public void setPeriodEnd(LocalDate periodEnd) {
    this.periodEnd = periodEnd;
  }

  public String getContentMarkdown() {
    return contentMarkdown;
  }

  public void setContentMarkdown(String contentMarkdown) {
    this.contentMarkdown = contentMarkdown;
  }

  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public Instant getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(Instant createdAt) {
    this.createdAt = createdAt;
  }

  public Instant getAcceptedAt() {
    return acceptedAt;
  }

  public void setAcceptedAt(Instant acceptedAt) {
    this.acceptedAt = acceptedAt;
  }
}
