/* (C) 2026 Rainier — internal use only. */
package com.rainier.common.persistence;

import java.time.Instant;
import javax.persistence.Column;
import javax.persistence.EntityListeners;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;
import org.hibernate.annotations.GenericGenerator;
import org.springframework.data.annotation.CreatedBy;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedBy;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

/**
 * Common columns inherited by every {@code rainier_*} entity.
 *
 * <p>Audit fields ({@code create_by} / {@code create_time} / {@code update_by} / {@code
 * update_time}) are populated by {@link AuditingEntityListener} reading {@link AuditorAwareImpl}.
 *
 * <p>The {@code del_flag} column is part of the global soft-delete pattern (see design.md §6).
 * Entities that opt into soft delete add {@code @SQLDelete} + {@code @Where("del_flag = 0")} on the
 * concrete subclass; entities that prefer hard delete (e.g. {@code UserOrganization}) leave those
 * annotations off — the column still exists but stays {@code false}.
 *
 * <p>Identifiers are 32-char UUID hex strings (no dashes), generated by Hibernate's {@code
 * UUIDHexGenerator} (alias {@code "uuid"}).
 */
@MappedSuperclass
@EntityListeners(AuditingEntityListener.class)
public abstract class BaseEntity {

  @Id
  @GeneratedValue(generator = "uuid-hex")
  @GenericGenerator(name = "uuid-hex", strategy = "uuid")
  @Column(length = 32, nullable = false, updatable = false)
  private String id;

  @CreatedBy
  @Column(name = "create_by", length = 32, updatable = false)
  private String createBy;

  @CreatedDate
  @Column(name = "create_time", nullable = false, updatable = false)
  private Instant createTime;

  @LastModifiedBy
  @Column(name = "update_by", length = 32)
  private String updateBy;

  @LastModifiedDate
  @Column(name = "update_time", nullable = false)
  private Instant updateTime;

  @Column(name = "del_flag", nullable = false)
  private Boolean delFlag = Boolean.FALSE;

  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public String getCreateBy() {
    return createBy;
  }

  public void setCreateBy(String createBy) {
    this.createBy = createBy;
  }

  public Instant getCreateTime() {
    return createTime;
  }

  public void setCreateTime(Instant createTime) {
    this.createTime = createTime;
  }

  public String getUpdateBy() {
    return updateBy;
  }

  public void setUpdateBy(String updateBy) {
    this.updateBy = updateBy;
  }

  public Instant getUpdateTime() {
    return updateTime;
  }

  public void setUpdateTime(Instant updateTime) {
    this.updateTime = updateTime;
  }

  public Boolean getDelFlag() {
    return delFlag;
  }

  public void setDelFlag(Boolean delFlag) {
    this.delFlag = delFlag;
  }
}
